### PR TITLE
Add ability to include/change backend headers in event

### PR DESCRIPTION
**Pull request by Jack28**
Before it was not possible to change the header within the email backend.

For example: 
Customized headers can be used to provide more information to the system receiving the email message.

Now a configuration allows headers that can be set/overwritten by the event body.

This includes an architectural change:
We define a new base class 'Backend' that every backend needs to implement.
It specifies how sub classes have to be structured and the steps every backend performs.

### CODE REVIEW

**Comment by DarkS0ul3** [comment]
test/test.py is outputting an error regarding pyotrs (not installed) -> might be beneficial to add pyotrs to requirements.txt or adjust test.py

**Comment by Jack28** [comment]
pyotrs is an optional dependecy. There is no need to install the package on a system that uses a different backend.
It is documented in the installation instructions so it should be fine.
We could include a hint on how to run the test suite or make the test suite fail early with a better error message.

I wouldn't want to run only tests with installed requirements but maybe you have think different. Let me know

**Comment by DarkS0ul3** [comment]
A hint regarding the testsuite seems like a good idea here, the error message is already meaningful enough in my opinion ;)

**Comment by Jack28** [comment]
Thank you for making me write documentation. It is important they say

**Comment by Jack28** [comment]
I am waiting for you to criticize that I’m no longer pinning the package version as we discuss in #4 
The big difference and the recomendations online seem to be:
if you write a library you specify requirements, hence >1.1 and !1.2 according to your knowing with which version your library works. But if you write an application you should pin the exact version and use a dependency tracking system (e.g. dependabot).

**Comment by DarkS0ul3** [comment]
Well, the requirements.txt file didn't change, so the version pinning should be fine i guess? Regarding the dev-requirements.txt there was no version pinning before but it might make sense to add versions here :D.

**Review by DarkS0ul3 — APPROVED** [review]
Seems fine to me

**Pull request merged**
